language: python
python:
  - "3.6"

services:
  - docker

before_install:
  - docker-compose version

install:
  - pip install -r requirements.txt

before_script:
  - docker-compose up

script:
  - nosetests

after_script:
  - docker-compose down