version: "3"
services:
  db:
    image: postgres
    expose:
      - "5432"
    env_file:
      - .env
  server:
    build: server
    volumes:
      - ./server:/work
    expose:
      - "5000"
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env
    command: >
      /bin/sh -c "sleep 5 &&
                  python run.py db upgrade &&
                  python run.py runserver --host 0.0.0.0"
  frontend:
    build: frontend
    environment:
      - HOST=0.0.0.0
    volumes:
      - ./frontend/src:/work/src
    ports:
      - "8080:8080"
    depends_on:
      - server

